# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0c34b107f274d3f0b1d3c0e9cc5b6d40b36afe032dbae6e4057ec86dd9695db655801eeb3e927b0054198772b8f4030bc67ddc4728e89993af21c3f8a25f6b4

test:
  secret_key_base: e5aa189723f900d5073d1c58459171a9683b0f10c70e4f701685167fc093edefca10aec246c14b1df7493b50ec9fd92d2c330eef49e7f247204c65f562293890

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
